### PR TITLE
Publish views

### PR DESCRIPTION
**Pull request by xAockd**
Publish views for more flexibility

### CODE REVIEW

**Comment by dwightwatson** [comment]
Happy for this, but curious for the use case. What sort of flexibility to you need with the views?

**Comment by xAockd** [comment]
I want to add one more view and extend for 1 more method. Would be good to keep all views related to the package in one place. Does it make sense to you?

**Comment by dwightwatson** [comment]
Cool, fair enough. I figured it would have to involve you extending the builder somehow because I wasn't sure what else you could do with the views. I'll tag a new release in a bit.

**Comment by xAockd** [comment]
Big thanks!

Cheers!

**Pull request merged**
